function run040511()
global pdStim screen

try
    CreateStimuliLogStart();
    
    
    % Define the rectangles
    [screenX, screenY] = Screen('WindowSize', max(Screen('Screens')));
    center1 =[screenX screenY]/2;    
    objRect1 = GetRects(192, center1);

    Wait2Start('debugging',0)

    barsWidth = 8;
    backTex = GetBarsTex(768, barsWidth, screen, 1);
    
    pdStim = 0;
    %pause(1)
    UflickerObj( ...
        'objContrast', [.03 .06 .12 .24 1], ...
        'rects', objRect1, ...
        'backMode', [0 0 1 0], ...
        'backTexture', backTex, ...
        'barsWidth', barsWidth, ...
        'backReverseFreq', 1, ...
        'backJitterPeriod', 10, ...
        'objJitterPeriod', 10, ...
        'presentationLength', 10, ...
        'movieDurationSecs', 1600 ...
        );
        
    barsWidth = 16;
    backTex = GetCheckersTex(768, barsWidth, screen, 1);
    pdStim = 1;
    %pause(1)
    UflickerObj( ...
        'objContrast', [.03 .06 .12 .24 1], ...
        'rects', objRect1, ...
        'backMode', [0 0 1 0], ...
        'backTexture', backTex, ...
        'barsWidth', barsWidth, ...
        'backReverseFreq', 1, ...
        'backJitterPeriod', 10, ...
        'objJitterPeriod', 10, ...
        'presentationLength', 10, ...
        'movieDurationSecs', 1600 ...
        );

    CreateStimuliLogWrite();

catch
    FinishExperiment();
    psychrethrow(psychlasterror);
end %try..catch..
end
