function GetPassword()
h = figure(1);
hp = uipanel('Title','Main Panel','FontSize',12,...
             'BackgroundColor','white',...
             'Position',[.25 .1 .67 .67]);

label1 = uicontrol('Parent',hp,'String','email address',...
              'Position',[1 200 100 36]);          
h1 = uicontrol('Parent',hp,'Style','edit','String','jadz@stanford.edu',...
              'Position',[105 200 200 36]);
label2 = uicontrol('Parent',hp,'String','Password',...
              'Position',[1 100 100 36]);          
h2 = uicontrol('Parent',hp,'Style','edit',...
              'Position',[105 100 200 36]);
end          