function S = EnterCellsAndSizes()

    S.fh = figure('units','pixels',...
                  'position',[450 450 400 200],...
                  'menubar','none',...
                  'name','Verify Password.',...
                  'resize','off',...
                  'numbertitle','off',...
                  'name','GUI_4', ...
                  'DeleteFcn', {@returnCells});
    S.ls = uicontrol('style','list',...
                     'units','pix',...
                     'position',[210 60 180 120],...
                     'backgroundcolor','w',...
                     'HorizontalAlign','left');
    S.add = uicontrol('style','push',...
                     'units','pix',...
                     'position',[10 10 50 40],...
                     'HorizontalAlign','left',...
                     'string','Add',...
                     'fontsize',14,'fontweight','bold',...
                     'callback',{@add,S});
    S.delete = uicontrol('style','push',...
                     'units','pix',...
                     'position',[60 10 80 40],...
                     'HorizontalAlign','left',...
                     'string','Delete',...
                     'fontsize',14,'fontweight','bold',...
                     'callback',{@delete,S});
    S.all = uicontrol('style','push',...
                     'units','pix',...
                     'position',[140 10 50 40],...
                     'HorizontalAlign','left',...
                     'string','All',...
                     'fontsize',14,'fontweight','bold',...
                     'callback',{@pb_call,S});
    S.first = uicontrol('style','push',...
                     'units','pix',...
                     'position',[190 10 80 40],...
                     'HorizontalAlign','left',...
                     'string','First',...
                     'fontsize',14,'fontweight','bold',...
                     'callback',{@pb_call,S});
    S.next = uicontrol('style','push',...
                     'units','pix',...
                     'position',[270 10 80 40],...
                     'HorizontalAlign','left',...
                     'string','Next',...
                     'fontsize',14,'fontweight','bold',...
                     'callback',{@next,S});

end

function [] = add(varargin)
    % Add cell to list
    S = varargin{3};
    data = guidata(S.fh);
    if isempty(data)
        data = InitStruct(data);
    end
    data.centers = [data.centers; rand rand];
    data.sizes = [data.sizes; rand];
    data.cellsN = data.cellsN+1;
    data.current = data.current+1;
    guidata(S.fh, data)
end

function [data] = InitStruct(data)
    data.current = 0;
    data.cellsN = 0;
    data.centers=[];
    data.sizes=[];
end

function [] = delete(varargin)
    % Delete current cell
    S = varargin{3};
    data = guidata(S.fh);
    current = data.current;
    data.centers(current, :) = [];
    data.sizes(current) = [];
    data.cellsN = data.cellsN-1;
    data.current = data.current-1;
    guidata(S.fh, data)
end

function [] = next(varargin)
    % Delete current cell
    S = varargin{3};
    data = guidata(S.fh);
    data.current = mod(data.current-1, data.cellsN+1);
    guidata(S.fh, data)
end

function data = returnCells(varargin)
    global data
    h = gcbo;
    data = guidata(h);
end
